<?php

return [
    'name' => 'Laravel Admin Module',
    'system-navigation'=>[
       'name'=>'System',
        'enabled'=>true,
    ],
    'models'=>[
        'Module'=>[
            'icon'=>'heroicon-o-cube'
        ],
        'Comment'=>[
            'icon'=>'heroicon-o-chat'
        ],
        'Coupon'=>[
            'icon'=>'heroicon-o-gift'
        ],
        'Extra'=>[
            'icon'=>'heroicon-o-view-grid-add'
        ],
        'Phone'=>[
            'icon'=>'heroicon-o-phone'
        ],
        'Address'=>[
            'icon'=>'heroicon-o-at-symbol'
        ],
        'Rating'=>[
            'icon'=>'heroicon-o-star'
        ],
        'Price'=>[
            'icon'=>'heroicon-o-currency-dollar'
        ],
        'Tag'=>[
            'icon'=>'heroicon-o-tag'
        ],
    ],
    'navigation'=>[
        'name'=>'Utilities',
        'enabled'=>true,
    ],
];
